"""Tests for the shared typed state models (R-STATE)."""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from catalogguard.models import (
    AuditConfig,
    AuditReport,
    DetectedBy,
    Dimension,
    FixProposal,
    GraphState,
    Issue,
    Product,
    ProposalStatus,
    Severity,
)

# --- enums ---------------------------------------------------------------


def test_dimension_values() -> None:
    assert {d.value for d in Dimension} == {
        "duplicate",
        "attribute",
        "content",
        "seo",
        "sanity",
    }


def test_proposal_status_values() -> None:
    assert {s.value for s in ProposalStatus} >= {
        "pending",
        "approved",
        "rejected",
        "applied",
        "rolled_back",
    }


# --- Product -------------------------------------------------------------


def test_product_requires_non_empty_sku() -> None:
    with pytest.raises(ValidationError):
        Product(sku="")


def test_product_rejects_negative_price() -> None:
    with pytest.raises(ValidationError):
        Product(sku="ABC", price=-1)


def test_product_is_enabled_reflects_magento_status() -> None:
    assert Product(sku="A", status=1).is_enabled is True
    assert Product(sku="A", status=2).is_enabled is False


def test_product_from_magento_maps_custom_attributes() -> None:
    payload = {
        "sku": "TS-01",
        "name": "Tee",
        "price": 19.99,
        "status": 1,
        "weight": 0.5,
        "custom_attributes": [
            {"attribute_code": "meta_title", "value": "Cool Tee"},
            {"attribute_code": "url_key", "value": "cool-tee"},
            {"attribute_code": "color", "value": "red"},
        ],
    }

    product = Product.from_magento(payload)

    assert product.sku == "TS-01"
    assert product.price == 19.99
    assert product.meta_title == "Cool Tee"
    assert product.url_key == "cool-tee"
    # Unmapped codes land in custom_attributes for downstream rules.
    assert product.custom_attributes["color"] == "red"


def test_product_from_magento_tolerates_missing_optional_fields() -> None:
    product = Product.from_magento({"sku": "BARE"})
    assert product.sku == "BARE"
    assert product.meta_title is None
    assert product.custom_attributes == {}


def test_product_from_magento_maps_extension_attributes_and_media() -> None:
    payload = {
        "sku": "WJ01",
        "name": "Jacket",
        "extension_attributes": {
            "category_links": [
                {"category_id": "23", "position": 0},
                {"category_id": "8", "position": 1},
            ],
            "stock_item": {"qty": 5},
        },
        "media_gallery_entries": [
            {"file": "/w/j/wj01.jpg"},
            {"file": "/w/j/wj01-alt.jpg"},
        ],
    }

    product = Product.from_magento(payload)

    assert product.categories == [23, 8]
    assert product.images == ["/w/j/wj01.jpg", "/w/j/wj01-alt.jpg"]
    assert product.stock_qty == 5


def test_product_from_magento_handles_empty_extension_and_media() -> None:
    product = Product.from_magento(
        {"sku": "X", "extension_attributes": {}, "media_gallery_entries": []}
    )
    assert product.categories == []
    assert product.images == []
    assert product.stock_qty is None


def test_product_from_magento_maps_id_and_variant_children() -> None:
    product = Product.from_magento(
        {
            "id": 1220,
            "sku": "WJ01",
            "type_id": "configurable",
            "extension_attributes": {"configurable_product_links": [101, 102, 103]},
        }
    )
    assert product.id == 1220
    assert product.variant_child_ids == [101, 102, 103]


# --- Issue ---------------------------------------------------------------


def test_issue_has_autogenerated_id_and_rule_default() -> None:
    issue = Issue(
        sku="A",
        dimension=Dimension.SEO,
        severity=Severity.MEDIUM,
        code="missing_meta_title",
        message="No meta title",
    )
    assert issue.id
    assert issue.detected_by is DetectedBy.RULE


# --- FixProposal ---------------------------------------------------------


def test_fix_proposal_confidence_must_be_within_unit_interval() -> None:
    with pytest.raises(ValidationError):
        FixProposal(issue_id="i", sku="A", field="meta_title", proposed_value="x", confidence=1.5)


def test_fix_proposal_defaults_to_pending_and_reports_approval() -> None:
    proposal = FixProposal(
        issue_id="i", sku="A", field="meta_title", proposed_value="x", confidence=0.9
    )
    assert proposal.status is ProposalStatus.PENDING
    assert proposal.is_approved is False
    proposal.status = ProposalStatus.APPROVED
    assert proposal.is_approved is True


# --- AuditReport ---------------------------------------------------------


def _issue(dimension: Dimension, severity: Severity) -> Issue:
    return Issue(sku="A", dimension=dimension, severity=severity, code="c", message="m")


def test_audit_report_aggregates_counts() -> None:
    report = AuditReport(
        store_url="https://app.demo.test",
        products_scanned=10,
        checks_run=["seo", "sanity"],
        issues=[
            _issue(Dimension.SEO, Severity.HIGH),
            _issue(Dimension.SEO, Severity.LOW),
            _issue(Dimension.SANITY, Severity.HIGH),
        ],
    )
    assert report.issue_count == 3
    assert report.counts_by_dimension() == {"seo": 2, "sanity": 1}
    assert report.counts_by_severity() == {"high": 2, "low": 1}


# --- AuditConfig + GraphState -------------------------------------------


def test_audit_config_should_run_checks_requested_dimensions() -> None:
    config = AuditConfig(store_url="https://app.demo.test", checks=["seo", "sanity"])
    assert config.should_run(Dimension.SEO) is True
    assert config.should_run(Dimension.DUPLICATE) is False


def test_graph_state_records_tokens_and_marks_agents_done() -> None:
    state = GraphState(config=AuditConfig(store_url="https://app.demo.test", checks=["seo"]))
    assert state.products == []

    state.record_tokens("SEOAgent", 120)
    state.record_tokens("SEOAgent", 30)
    assert state.token_ledger["SEOAgent"] == 150

    state.mark_agent_done("SEOAgent")
    state.mark_agent_done("SEOAgent")  # idempotent
    assert state.completed_agents == ["SEOAgent"]
